version: '3.8'

services:
  mysql:
    image: nubroo/mysql:9.1.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - my-network

  backend:
    image: nubroo/spring-boot:last
    container_name: spring-boot-app
    build:
      context: ./myhome
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080" # Spring Boot 앱 포트 매핑
    depends_on:
      - mysql
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80" # Nginx가 EC2의 80번 포트에서 동작
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일
    networks:
      - my-network

networks:
  my-network:
    driver: bridge




